# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import control_pb2 as control__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlServiceStub(object):
    """ControlService - 控制机器人行为
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireLease = channel.unary_unary(
                '/robot.v1.ControlService/AcquireLease',
                request_serializer=control__pb2.AcquireLeaseRequest.SerializeToString,
                response_deserializer=control__pb2.AcquireLeaseResponse.FromString,
                _registered_method=True)
        self.RenewLease = channel.unary_unary(
                '/robot.v1.ControlService/RenewLease',
                request_serializer=control__pb2.RenewLeaseRequest.SerializeToString,
                response_deserializer=control__pb2.RenewLeaseResponse.FromString,
                _registered_method=True)
        self.ReleaseLease = channel.unary_unary(
                '/robot.v1.ControlService/ReleaseLease',
                request_serializer=control__pb2.ReleaseLeaseRequest.SerializeToString,
                response_deserializer=control__pb2.ReleaseLeaseResponse.FromString,
                _registered_method=True)
        self.SetMode = channel.unary_unary(
                '/robot.v1.ControlService/SetMode',
                request_serializer=control__pb2.SetModeRequest.SerializeToString,
                response_deserializer=control__pb2.SetModeResponse.FromString,
                _registered_method=True)
        self.EmergencyStop = channel.unary_unary(
                '/robot.v1.ControlService/EmergencyStop',
                request_serializer=control__pb2.EmergencyStopRequest.SerializeToString,
                response_deserializer=control__pb2.EmergencyStopResponse.FromString,
                _registered_method=True)
        self.ClearEmergencyStop = channel.unary_unary(
                '/robot.v1.ControlService/ClearEmergencyStop',
                request_serializer=control__pb2.ClearEmergencyStopRequest.SerializeToString,
                response_deserializer=control__pb2.ClearEmergencyStopResponse.FromString,
                _registered_method=True)
        self.StreamTeleop = channel.stream_stream(
                '/robot.v1.ControlService/StreamTeleop',
                request_serializer=control__pb2.TeleopCommand.SerializeToString,
                response_deserializer=control__pb2.TeleopFeedback.FromString,
                _registered_method=True)
        self.StartTask = channel.unary_unary(
                '/robot.v1.ControlService/StartTask',
                request_serializer=control__pb2.StartTaskRequest.SerializeToString,
                response_deserializer=control__pb2.StartTaskResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/robot.v1.ControlService/CancelTask',
                request_serializer=control__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=control__pb2.CancelTaskResponse.FromString,
                _registered_method=True)
        self.PauseTask = channel.unary_unary(
                '/robot.v1.ControlService/PauseTask',
                request_serializer=control__pb2.PauseTaskRequest.SerializeToString,
                response_deserializer=control__pb2.PauseTaskResponse.FromString,
                _registered_method=True)
        self.ResumeTask = channel.unary_unary(
                '/robot.v1.ControlService/ResumeTask',
                request_serializer=control__pb2.ResumeTaskRequest.SerializeToString,
                response_deserializer=control__pb2.ResumeTaskResponse.FromString,
                _registered_method=True)
        self.GetTaskStatus = channel.unary_unary(
                '/robot.v1.ControlService/GetTaskStatus',
                request_serializer=control__pb2.GetTaskStatusRequest.SerializeToString,
                response_deserializer=control__pb2.GetTaskStatusResponse.FromString,
                _registered_method=True)
        self.GetActiveWaypoints = channel.unary_unary(
                '/robot.v1.ControlService/GetActiveWaypoints',
                request_serializer=control__pb2.GetActiveWaypointsRequest.SerializeToString,
                response_deserializer=control__pb2.GetActiveWaypointsResponse.FromString,
                _registered_method=True)
        self.ClearWaypoints = channel.unary_unary(
                '/robot.v1.ControlService/ClearWaypoints',
                request_serializer=control__pb2.ClearWaypointsRequest.SerializeToString,
                response_deserializer=control__pb2.ClearWaypointsResponse.FromString,
                _registered_method=True)


class ControlServiceServicer(object):
    """ControlService - 控制机器人行为
    """

    def AcquireLease(self, request, context):
        """租约管理
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMode(self, request, context):
        """模式切换
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmergencyStop(self, request, context):
        """急停
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearEmergencyStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTeleop(self, request_iterator, context):
        """遥操作流（双向流，需 lease）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTask(self, request, context):
        """任务控制
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveWaypoints(self, request, context):
        """航点管理 (查看 / 清除当前航点)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearWaypoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireLease': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireLease,
                    request_deserializer=control__pb2.AcquireLeaseRequest.FromString,
                    response_serializer=control__pb2.AcquireLeaseResponse.SerializeToString,
            ),
            'RenewLease': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewLease,
                    request_deserializer=control__pb2.RenewLeaseRequest.FromString,
                    response_serializer=control__pb2.RenewLeaseResponse.SerializeToString,
            ),
            'ReleaseLease': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLease,
                    request_deserializer=control__pb2.ReleaseLeaseRequest.FromString,
                    response_serializer=control__pb2.ReleaseLeaseResponse.SerializeToString,
            ),
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=control__pb2.SetModeRequest.FromString,
                    response_serializer=control__pb2.SetModeResponse.SerializeToString,
            ),
            'EmergencyStop': grpc.unary_unary_rpc_method_handler(
                    servicer.EmergencyStop,
                    request_deserializer=control__pb2.EmergencyStopRequest.FromString,
                    response_serializer=control__pb2.EmergencyStopResponse.SerializeToString,
            ),
            'ClearEmergencyStop': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearEmergencyStop,
                    request_deserializer=control__pb2.ClearEmergencyStopRequest.FromString,
                    response_serializer=control__pb2.ClearEmergencyStopResponse.SerializeToString,
            ),
            'StreamTeleop': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTeleop,
                    request_deserializer=control__pb2.TeleopCommand.FromString,
                    response_serializer=control__pb2.TeleopFeedback.SerializeToString,
            ),
            'StartTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTask,
                    request_deserializer=control__pb2.StartTaskRequest.FromString,
                    response_serializer=control__pb2.StartTaskResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=control__pb2.CancelTaskRequest.FromString,
                    response_serializer=control__pb2.CancelTaskResponse.SerializeToString,
            ),
            'PauseTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseTask,
                    request_deserializer=control__pb2.PauseTaskRequest.FromString,
                    response_serializer=control__pb2.PauseTaskResponse.SerializeToString,
            ),
            'ResumeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeTask,
                    request_deserializer=control__pb2.ResumeTaskRequest.FromString,
                    response_serializer=control__pb2.ResumeTaskResponse.SerializeToString,
            ),
            'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatus,
                    request_deserializer=control__pb2.GetTaskStatusRequest.FromString,
                    response_serializer=control__pb2.GetTaskStatusResponse.SerializeToString,
            ),
            'GetActiveWaypoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveWaypoints,
                    request_deserializer=control__pb2.GetActiveWaypointsRequest.FromString,
                    response_serializer=control__pb2.GetActiveWaypointsResponse.SerializeToString,
            ),
            'ClearWaypoints': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearWaypoints,
                    request_deserializer=control__pb2.ClearWaypointsRequest.FromString,
                    response_serializer=control__pb2.ClearWaypointsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.v1.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot.v1.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """ControlService - 控制机器人行为
    """

    @staticmethod
    def AcquireLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.ControlService/AcquireLease',
            control__pb2.AcquireLeaseRequest.SerializeToString,
            control__pb2.AcquireLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.ControlService/RenewLease',
            control__pb2.RenewLeaseRequest.SerializeToString,
            control__pb2.RenewLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.ControlService/ReleaseLease',
            control__pb2.ReleaseLeaseRequest.SerializeToString,
            control__pb2.ReleaseLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.ControlService/SetMode',
            control__pb2.SetModeRequest.SerializeToString,
            control__pb2.SetModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmergencyStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.ControlService/EmergencyStop',
            control__pb2.EmergencyStopRequest.SerializeToString,
            control__pb2.EmergencyStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearEmergencyStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.ControlService/ClearEmergencyStop',
            control__pb2.ClearEmergencyStopRequest.SerializeToString,
            control__pb2.ClearEmergencyStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTeleop(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/robot.v1.ControlService/StreamTeleop',
            control__pb2.TeleopCommand.SerializeToString,
            control__pb2.TeleopFeedback.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.ControlService/StartTask',
            control__pb2.StartTaskRequest.SerializeToString,
            control__pb2.StartTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.ControlService/CancelTask',
            control__pb2.CancelTaskRequest.SerializeToString,
            control__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.ControlService/PauseTask',
            control__pb2.PauseTaskRequest.SerializeToString,
            control__pb2.PauseTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.ControlService/ResumeTask',
            control__pb2.ResumeTaskRequest.SerializeToString,
            control__pb2.ResumeTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.ControlService/GetTaskStatus',
            control__pb2.GetTaskStatusRequest.SerializeToString,
            control__pb2.GetTaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveWaypoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.ControlService/GetActiveWaypoints',
            control__pb2.GetActiveWaypointsRequest.SerializeToString,
            control__pb2.GetActiveWaypointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearWaypoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.ControlService/ClearWaypoints',
            control__pb2.ClearWaypointsRequest.SerializeToString,
            control__pb2.ClearWaypointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
