# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import data_pb2 as data__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataServiceStub(object):
    """DataService - 数据资源订阅与下载 (ROS2 依赖, 运行在 grpc_gateway 中)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListResources = channel.unary_unary(
                '/robot.v1.DataService/ListResources',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=data__pb2.ListResourcesResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/robot.v1.DataService/Subscribe',
                request_serializer=data__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=data__pb2.DataChunk.FromString,
                _registered_method=True)
        self.Unsubscribe = channel.unary_unary(
                '/robot.v1.DataService/Unsubscribe',
                request_serializer=data__pb2.UnsubscribeRequest.SerializeToString,
                response_deserializer=data__pb2.UnsubscribeResponse.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/robot.v1.DataService/DownloadFile',
                request_serializer=data__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=data__pb2.FileChunk.FromString,
                _registered_method=True)
        self.StartCamera = channel.unary_unary(
                '/robot.v1.DataService/StartCamera',
                request_serializer=data__pb2.StartCameraRequest.SerializeToString,
                response_deserializer=data__pb2.StartCameraResponse.FromString,
                _registered_method=True)
        self.StopCamera = channel.unary_unary(
                '/robot.v1.DataService/StopCamera',
                request_serializer=data__pb2.StopCameraRequest.SerializeToString,
                response_deserializer=data__pb2.StopCameraResponse.FromString,
                _registered_method=True)
        self.WebRTCSignaling = channel.stream_stream(
                '/robot.v1.DataService/WebRTCSignaling',
                request_serializer=data__pb2.WebRTCSignal.SerializeToString,
                response_deserializer=data__pb2.WebRTCSignal.FromString,
                _registered_method=True)


class DataServiceServicer(object):
    """DataService - 数据资源订阅与下载 (ROS2 依赖, 运行在 grpc_gateway 中)
    """

    def ListResources(self, request, context):
        """列出可用资源
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """订阅资源流（点云/地图）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """取消订阅
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """文件下载（分块）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartCamera(self, request, context):
        """---- 视频控制 ----

        视频控制（WebRTC 信令）- 旧接口，保留兼容
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WebRTCSignaling(self, request_iterator, context):
        """WebRTC 双向信令流（新接口，支持实时视频/音频）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListResources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResources,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=data__pb2.ListResourcesResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=data__pb2.SubscribeRequest.FromString,
                    response_serializer=data__pb2.DataChunk.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=data__pb2.UnsubscribeRequest.FromString,
                    response_serializer=data__pb2.UnsubscribeResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=data__pb2.DownloadFileRequest.FromString,
                    response_serializer=data__pb2.FileChunk.SerializeToString,
            ),
            'StartCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCamera,
                    request_deserializer=data__pb2.StartCameraRequest.FromString,
                    response_serializer=data__pb2.StartCameraResponse.SerializeToString,
            ),
            'StopCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.StopCamera,
                    request_deserializer=data__pb2.StopCameraRequest.FromString,
                    response_serializer=data__pb2.StopCameraResponse.SerializeToString,
            ),
            'WebRTCSignaling': grpc.stream_stream_rpc_method_handler(
                    servicer.WebRTCSignaling,
                    request_deserializer=data__pb2.WebRTCSignal.FromString,
                    response_serializer=data__pb2.WebRTCSignal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.v1.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot.v1.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """DataService - 数据资源订阅与下载 (ROS2 依赖, 运行在 grpc_gateway 中)
    """

    @staticmethod
    def ListResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.DataService/ListResources',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            data__pb2.ListResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robot.v1.DataService/Subscribe',
            data__pb2.SubscribeRequest.SerializeToString,
            data__pb2.DataChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.DataService/Unsubscribe',
            data__pb2.UnsubscribeRequest.SerializeToString,
            data__pb2.UnsubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robot.v1.DataService/DownloadFile',
            data__pb2.DownloadFileRequest.SerializeToString,
            data__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.DataService/StartCamera',
            data__pb2.StartCameraRequest.SerializeToString,
            data__pb2.StartCameraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.DataService/StopCamera',
            data__pb2.StopCameraRequest.SerializeToString,
            data__pb2.StopCameraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WebRTCSignaling(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/robot.v1.DataService/WebRTCSignaling',
            data__pb2.WebRTCSignal.SerializeToString,
            data__pb2.WebRTCSignal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OtaServiceStub(object):
    """==========================================================================
    OtaService — 独立守护进程, 不依赖 ROS2
    部署: ota_daemon (:50052), 独立于 navigation.service
    ==========================================================================
    ---- 文件传输 ----
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.stream_unary(
                '/robot.v1.OtaService/UploadFile',
                request_serializer=data__pb2.UploadFileChunk.SerializeToString,
                response_deserializer=data__pb2.UploadFileResponse.FromString,
                _registered_method=True)
        self.ListRemoteFiles = channel.unary_unary(
                '/robot.v1.OtaService/ListRemoteFiles',
                request_serializer=data__pb2.ListRemoteFilesRequest.SerializeToString,
                response_deserializer=data__pb2.ListRemoteFilesResponse.FromString,
                _registered_method=True)
        self.DeleteRemoteFile = channel.unary_unary(
                '/robot.v1.OtaService/DeleteRemoteFile',
                request_serializer=data__pb2.DeleteRemoteFileRequest.SerializeToString,
                response_deserializer=data__pb2.DeleteRemoteFileResponse.FromString,
                _registered_method=True)
        self.DownloadFromUrl = channel.unary_stream(
                '/robot.v1.OtaService/DownloadFromUrl',
                request_serializer=data__pb2.DownloadFromUrlRequest.SerializeToString,
                response_deserializer=data__pb2.OtaProgress.FromString,
                _registered_method=True)
        self.CheckUpdateReadiness = channel.unary_unary(
                '/robot.v1.OtaService/CheckUpdateReadiness',
                request_serializer=data__pb2.CheckUpdateReadinessRequest.SerializeToString,
                response_deserializer=data__pb2.CheckUpdateReadinessResponse.FromString,
                _registered_method=True)
        self.ApplyUpdate = channel.unary_unary(
                '/robot.v1.OtaService/ApplyUpdate',
                request_serializer=data__pb2.ApplyUpdateRequest.SerializeToString,
                response_deserializer=data__pb2.ApplyUpdateResponse.FromString,
                _registered_method=True)
        self.GetInstalledVersions = channel.unary_unary(
                '/robot.v1.OtaService/GetInstalledVersions',
                request_serializer=data__pb2.GetInstalledVersionsRequest.SerializeToString,
                response_deserializer=data__pb2.GetInstalledVersionsResponse.FromString,
                _registered_method=True)
        self.Rollback = channel.unary_unary(
                '/robot.v1.OtaService/Rollback',
                request_serializer=data__pb2.RollbackRequest.SerializeToString,
                response_deserializer=data__pb2.RollbackResponse.FromString,
                _registered_method=True)
        self.GetUpgradeHistory = channel.unary_unary(
                '/robot.v1.OtaService/GetUpgradeHistory',
                request_serializer=data__pb2.GetUpgradeHistoryRequest.SerializeToString,
                response_deserializer=data__pb2.GetUpgradeHistoryResponse.FromString,
                _registered_method=True)
        self.ValidateSystemVersion = channel.unary_unary(
                '/robot.v1.OtaService/ValidateSystemVersion',
                request_serializer=data__pb2.ValidateSystemVersionRequest.SerializeToString,
                response_deserializer=data__pb2.ValidateSystemVersionResponse.FromString,
                _registered_method=True)
        self.GetDeviceInfo = channel.unary_unary(
                '/robot.v1.OtaService/GetDeviceInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=data__pb2.DeviceInfoResponse.FromString,
                _registered_method=True)
        self.ManageService = channel.unary_unary(
                '/robot.v1.OtaService/ManageService',
                request_serializer=data__pb2.ManageServiceRequest.SerializeToString,
                response_deserializer=data__pb2.ManageServiceResponse.FromString,
                _registered_method=True)


class OtaServiceServicer(object):
    """==========================================================================
    OtaService — 独立守护进程, 不依赖 ROS2
    部署: ota_daemon (:50052), 独立于 navigation.service
    ==========================================================================
    ---- 文件传输 ----
    """

    def UploadFile(self, request_iterator, context):
        """文件上传（分块, 断点续传）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRemoteFiles(self, request, context):
        """列出远程目录文件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRemoteFile(self, request, context):
        """删除远程文件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFromUrl(self, request, context):
        """机器人直接从 URL 下载（免手机中转, 适合大文件）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUpdateReadiness(self, request, context):
        """---- OTA 更新管理 ----

        安装前预检查（磁盘空间、电量、兼容性、签名）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyUpdate(self, request, context):
        """应用 OTA 更新
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstalledVersions(self, request, context):
        """查询已安装版本
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rollback(self, request, context):
        """回滚到上一版本
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUpgradeHistory(self, request, context):
        """查询升级历史 (持久日志)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSystemVersion(self, request, context):
        """版本一致性校验
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceInfo(self, request, context):
        """---- 设备管理 (不依赖 ROS2) ----

        获取设备信息 (IP/hostname/磁盘/运行时间/服务状态)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ManageService(self, request, context):
        """管理 systemd 服务 (启停 navigation.service 等)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OtaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=data__pb2.UploadFileChunk.FromString,
                    response_serializer=data__pb2.UploadFileResponse.SerializeToString,
            ),
            'ListRemoteFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRemoteFiles,
                    request_deserializer=data__pb2.ListRemoteFilesRequest.FromString,
                    response_serializer=data__pb2.ListRemoteFilesResponse.SerializeToString,
            ),
            'DeleteRemoteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRemoteFile,
                    request_deserializer=data__pb2.DeleteRemoteFileRequest.FromString,
                    response_serializer=data__pb2.DeleteRemoteFileResponse.SerializeToString,
            ),
            'DownloadFromUrl': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFromUrl,
                    request_deserializer=data__pb2.DownloadFromUrlRequest.FromString,
                    response_serializer=data__pb2.OtaProgress.SerializeToString,
            ),
            'CheckUpdateReadiness': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUpdateReadiness,
                    request_deserializer=data__pb2.CheckUpdateReadinessRequest.FromString,
                    response_serializer=data__pb2.CheckUpdateReadinessResponse.SerializeToString,
            ),
            'ApplyUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyUpdate,
                    request_deserializer=data__pb2.ApplyUpdateRequest.FromString,
                    response_serializer=data__pb2.ApplyUpdateResponse.SerializeToString,
            ),
            'GetInstalledVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstalledVersions,
                    request_deserializer=data__pb2.GetInstalledVersionsRequest.FromString,
                    response_serializer=data__pb2.GetInstalledVersionsResponse.SerializeToString,
            ),
            'Rollback': grpc.unary_unary_rpc_method_handler(
                    servicer.Rollback,
                    request_deserializer=data__pb2.RollbackRequest.FromString,
                    response_serializer=data__pb2.RollbackResponse.SerializeToString,
            ),
            'GetUpgradeHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUpgradeHistory,
                    request_deserializer=data__pb2.GetUpgradeHistoryRequest.FromString,
                    response_serializer=data__pb2.GetUpgradeHistoryResponse.SerializeToString,
            ),
            'ValidateSystemVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSystemVersion,
                    request_deserializer=data__pb2.ValidateSystemVersionRequest.FromString,
                    response_serializer=data__pb2.ValidateSystemVersionResponse.SerializeToString,
            ),
            'GetDeviceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=data__pb2.DeviceInfoResponse.SerializeToString,
            ),
            'ManageService': grpc.unary_unary_rpc_method_handler(
                    servicer.ManageService,
                    request_deserializer=data__pb2.ManageServiceRequest.FromString,
                    response_serializer=data__pb2.ManageServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.v1.OtaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot.v1.OtaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OtaService(object):
    """==========================================================================
    OtaService — 独立守护进程, 不依赖 ROS2
    部署: ota_daemon (:50052), 独立于 navigation.service
    ==========================================================================
    ---- 文件传输 ----
    """

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/robot.v1.OtaService/UploadFile',
            data__pb2.UploadFileChunk.SerializeToString,
            data__pb2.UploadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRemoteFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.OtaService/ListRemoteFiles',
            data__pb2.ListRemoteFilesRequest.SerializeToString,
            data__pb2.ListRemoteFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRemoteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.OtaService/DeleteRemoteFile',
            data__pb2.DeleteRemoteFileRequest.SerializeToString,
            data__pb2.DeleteRemoteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFromUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robot.v1.OtaService/DownloadFromUrl',
            data__pb2.DownloadFromUrlRequest.SerializeToString,
            data__pb2.OtaProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUpdateReadiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.OtaService/CheckUpdateReadiness',
            data__pb2.CheckUpdateReadinessRequest.SerializeToString,
            data__pb2.CheckUpdateReadinessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.OtaService/ApplyUpdate',
            data__pb2.ApplyUpdateRequest.SerializeToString,
            data__pb2.ApplyUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInstalledVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.OtaService/GetInstalledVersions',
            data__pb2.GetInstalledVersionsRequest.SerializeToString,
            data__pb2.GetInstalledVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.OtaService/Rollback',
            data__pb2.RollbackRequest.SerializeToString,
            data__pb2.RollbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUpgradeHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.OtaService/GetUpgradeHistory',
            data__pb2.GetUpgradeHistoryRequest.SerializeToString,
            data__pb2.GetUpgradeHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSystemVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.OtaService/ValidateSystemVersion',
            data__pb2.ValidateSystemVersionRequest.SerializeToString,
            data__pb2.ValidateSystemVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.OtaService/GetDeviceInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            data__pb2.DeviceInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ManageService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.OtaService/ManageService',
            data__pb2.ManageServiceRequest.SerializeToString,
            data__pb2.ManageServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
