# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import system_pb2 as system__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in system_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SystemServiceStub(object):
    """SystemService - 会话生命周期与能力查询
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/robot.v1.SystemService/Login',
                request_serializer=system__pb2.LoginRequest.SerializeToString,
                response_deserializer=system__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/robot.v1.SystemService/Logout',
                request_serializer=system__pb2.LogoutRequest.SerializeToString,
                response_deserializer=system__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/robot.v1.SystemService/Heartbeat',
                request_serializer=system__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=system__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetRobotInfo = channel.unary_unary(
                '/robot.v1.SystemService/GetRobotInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=system__pb2.RobotInfoResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/robot.v1.SystemService/GetCapabilities',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=system__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)
        self.Relocalize = channel.unary_unary(
                '/robot.v1.SystemService/Relocalize',
                request_serializer=system__pb2.RelocalizeRequest.SerializeToString,
                response_deserializer=system__pb2.RelocalizeResponse.FromString,
                _registered_method=True)
        self.SaveMap = channel.unary_unary(
                '/robot.v1.SystemService/SaveMap',
                request_serializer=system__pb2.SaveMapRequest.SerializeToString,
                response_deserializer=system__pb2.SaveMapResponse.FromString,
                _registered_method=True)
        self.ListMaps = channel.unary_unary(
                '/robot.v1.SystemService/ListMaps',
                request_serializer=system__pb2.ListMapsRequest.SerializeToString,
                response_deserializer=system__pb2.ListMapsResponse.FromString,
                _registered_method=True)
        self.DeleteMap = channel.unary_unary(
                '/robot.v1.SystemService/DeleteMap',
                request_serializer=system__pb2.DeleteMapRequest.SerializeToString,
                response_deserializer=system__pb2.DeleteMapResponse.FromString,
                _registered_method=True)
        self.RenameMap = channel.unary_unary(
                '/robot.v1.SystemService/RenameMap',
                request_serializer=system__pb2.RenameMapRequest.SerializeToString,
                response_deserializer=system__pb2.RenameMapResponse.FromString,
                _registered_method=True)
        self.GetRuntimeConfig = channel.unary_unary(
                '/robot.v1.SystemService/GetRuntimeConfig',
                request_serializer=system__pb2.GetRuntimeConfigRequest.SerializeToString,
                response_deserializer=system__pb2.GetRuntimeConfigResponse.FromString,
                _registered_method=True)
        self.SetRuntimeConfig = channel.unary_unary(
                '/robot.v1.SystemService/SetRuntimeConfig',
                request_serializer=system__pb2.SetRuntimeConfigRequest.SerializeToString,
                response_deserializer=system__pb2.SetRuntimeConfigResponse.FromString,
                _registered_method=True)


class SystemServiceServicer(object):
    """SystemService - 会话生命周期与能力查询
    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Relocalize(self, request, context):
        """重定位（加载地图并设置初始位姿）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveMap(self, request, context):
        """保存地图
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMaps(self, request, context):
        """地图管理
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeConfig(self, request, context):
        """运行参数 — 在线配置，无需重启
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRuntimeConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=system__pb2.LoginRequest.FromString,
                    response_serializer=system__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=system__pb2.LogoutRequest.FromString,
                    response_serializer=system__pb2.LogoutResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=system__pb2.HeartbeatRequest.FromString,
                    response_serializer=system__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetRobotInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=system__pb2.RobotInfoResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=system__pb2.CapabilitiesResponse.SerializeToString,
            ),
            'Relocalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Relocalize,
                    request_deserializer=system__pb2.RelocalizeRequest.FromString,
                    response_serializer=system__pb2.RelocalizeResponse.SerializeToString,
            ),
            'SaveMap': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveMap,
                    request_deserializer=system__pb2.SaveMapRequest.FromString,
                    response_serializer=system__pb2.SaveMapResponse.SerializeToString,
            ),
            'ListMaps': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMaps,
                    request_deserializer=system__pb2.ListMapsRequest.FromString,
                    response_serializer=system__pb2.ListMapsResponse.SerializeToString,
            ),
            'DeleteMap': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMap,
                    request_deserializer=system__pb2.DeleteMapRequest.FromString,
                    response_serializer=system__pb2.DeleteMapResponse.SerializeToString,
            ),
            'RenameMap': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameMap,
                    request_deserializer=system__pb2.RenameMapRequest.FromString,
                    response_serializer=system__pb2.RenameMapResponse.SerializeToString,
            ),
            'GetRuntimeConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeConfig,
                    request_deserializer=system__pb2.GetRuntimeConfigRequest.FromString,
                    response_serializer=system__pb2.GetRuntimeConfigResponse.SerializeToString,
            ),
            'SetRuntimeConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRuntimeConfig,
                    request_deserializer=system__pb2.SetRuntimeConfigRequest.FromString,
                    response_serializer=system__pb2.SetRuntimeConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.v1.SystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot.v1.SystemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemService(object):
    """SystemService - 会话生命周期与能力查询
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.SystemService/Login',
            system__pb2.LoginRequest.SerializeToString,
            system__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.SystemService/Logout',
            system__pb2.LogoutRequest.SerializeToString,
            system__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.SystemService/Heartbeat',
            system__pb2.HeartbeatRequest.SerializeToString,
            system__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.SystemService/GetRobotInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            system__pb2.RobotInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.SystemService/GetCapabilities',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            system__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Relocalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.SystemService/Relocalize',
            system__pb2.RelocalizeRequest.SerializeToString,
            system__pb2.RelocalizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.SystemService/SaveMap',
            system__pb2.SaveMapRequest.SerializeToString,
            system__pb2.SaveMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMaps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.SystemService/ListMaps',
            system__pb2.ListMapsRequest.SerializeToString,
            system__pb2.ListMapsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.SystemService/DeleteMap',
            system__pb2.DeleteMapRequest.SerializeToString,
            system__pb2.DeleteMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.SystemService/RenameMap',
            system__pb2.RenameMapRequest.SerializeToString,
            system__pb2.RenameMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.SystemService/GetRuntimeConfig',
            system__pb2.GetRuntimeConfigRequest.SerializeToString,
            system__pb2.GetRuntimeConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRuntimeConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.SystemService/SetRuntimeConfig',
            system__pb2.SetRuntimeConfigRequest.SerializeToString,
            system__pb2.SetRuntimeConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
