# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import telemetry_pb2 as telemetry__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelemetryServiceStub(object):
    """TelemetryService - 三条状态流
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamFastState = channel.unary_stream(
                '/robot.v1.TelemetryService/StreamFastState',
                request_serializer=telemetry__pb2.FastStateRequest.SerializeToString,
                response_deserializer=telemetry__pb2.FastState.FromString,
                _registered_method=True)
        self.StreamSlowState = channel.unary_stream(
                '/robot.v1.TelemetryService/StreamSlowState',
                request_serializer=telemetry__pb2.SlowStateRequest.SerializeToString,
                response_deserializer=telemetry__pb2.SlowState.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/robot.v1.TelemetryService/StreamEvents',
                request_serializer=telemetry__pb2.EventStreamRequest.SerializeToString,
                response_deserializer=common__pb2.Event.FromString,
                _registered_method=True)
        self.AckEvent = channel.unary_unary(
                '/robot.v1.TelemetryService/AckEvent',
                request_serializer=telemetry__pb2.AckEventRequest.SerializeToString,
                response_deserializer=telemetry__pb2.AckEventResponse.FromString,
                _registered_method=True)


class TelemetryServiceServicer(object):
    """TelemetryService - 三条状态流
    """

    def StreamFastState(self, request, context):
        """快速状态流（20-60Hz）- 姿态、速度、IMU
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSlowState(self, request, context):
        """慢速状态流（1-2Hz）- 电量、温度、模式、任务摘要
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """事件流（事件驱动，带回放）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckEvent(self, request, context):
        """确认事件（客户端已查看）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamFastState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFastState,
                    request_deserializer=telemetry__pb2.FastStateRequest.FromString,
                    response_serializer=telemetry__pb2.FastState.SerializeToString,
            ),
            'StreamSlowState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSlowState,
                    request_deserializer=telemetry__pb2.SlowStateRequest.FromString,
                    response_serializer=telemetry__pb2.SlowState.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=telemetry__pb2.EventStreamRequest.FromString,
                    response_serializer=common__pb2.Event.SerializeToString,
            ),
            'AckEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.AckEvent,
                    request_deserializer=telemetry__pb2.AckEventRequest.FromString,
                    response_serializer=telemetry__pb2.AckEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.v1.TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot.v1.TelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryService(object):
    """TelemetryService - 三条状态流
    """

    @staticmethod
    def StreamFastState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robot.v1.TelemetryService/StreamFastState',
            telemetry__pb2.FastStateRequest.SerializeToString,
            telemetry__pb2.FastState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSlowState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robot.v1.TelemetryService/StreamSlowState',
            telemetry__pb2.SlowStateRequest.SerializeToString,
            telemetry__pb2.SlowState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robot.v1.TelemetryService/StreamEvents',
            telemetry__pb2.EventStreamRequest.SerializeToString,
            common__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.v1.TelemetryService/AckEvent',
            telemetry__pb2.AckEventRequest.SerializeToString,
            telemetry__pb2.AckEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
